defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
    permalink: /:basename
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Vortex Gallery
tagline: "Bring Your Own Mix."
description: "The largest community tournament in the FGC."
twitch: https://twitch.tv/956productions
twitter: 
  username: 956productions
  card: summary
logo: /img/logo.png
youtube: https://956pro.com/youtube
nav:
  - title: FAQ
    url: /faq
  - title: After Hours
    url: /afterhours
  - title: Results
    url: https://956.productions/results
volunteer: /volunteer
collections:
  - info
sponsors:
  - image: kaiten.png
    url: https://x.com/kaitenbooks
  - image: riichicity.png
    url: https://www.mahjong-jp.com/home
